# Generated by Django 5.1.4 on 2025-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffee_category_alter_coffee_image_alter_coffee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
