# Generated by Django 5.1.4 on 2025-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_coffee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=2080)),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.CharField(default='Uncategorized', max_length=2083),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pastry',
            name='image',
            field=models.URLField(default='Uncategorized', max_length=2080),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastry',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
