# Generated by Django 5.1.4 on 2025-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_tea_alter_coffee_image_alter_coffee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('sweet', 'Sweet'), ('savory', 'Savory')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.URLField(max_length=2080),
        ),
        migrations.AlterField(
            model_name='pastry',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('sweet', 'Sweet'), ('savory', 'Savory')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('sweet', 'Sweet'), ('savory', 'Savory')], max_length=100),
        ),
    ]
