# Generated by Django 5.1.4 on 2025-01-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_heroimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.URLField(max_length=2080),
        ),
    ]
